apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - name: feedback
          image: teamorigin/feedback
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-srv
spec:
  selector:
    app: feedback
  type: ClusterIP
  ports:
    - name: feedback
      protocol: TCP
      port: 5003
      targetPort: 5003
